# Generated by Django 5.2.5 on 2025-09-24 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LittlelemonAPI", "0002_category_menuitem_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="category",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                to="LittlelemonAPI.category",
            ),
        ),
    ]
